name: Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize, closed]

jobs:
  test:
    name: Build image
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      run: |
        echo "First Test"