name: Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize, closed]

jobs:
  pre-req:
    name: Setting up pre-req
    runs-on: ubuntu-latest
    outputs:
      SECRET_ENV: ${{ steps.secret-env.outputs.SECRET_ENV }}

    steps:

    - name: Set EnvVar for Secret
      id: secret-env
      run: |
        if [[ ${{ github.head_ref || github.ref_name }} == 'test-1' ]]; then
            echo "SECRET_ENV=PROD" >> "$GITHUB_OUTPUT"
        else
            echo "SECRET_ENV=DEV" >> "$GITHUB_OUTPUT"
        fi

  test:
    if: (!(github.event.action == 'closed' || github.event.pull_request.merged == true))
    needs: pre-req
    name: Create Infra
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Echo Env
      run: |
        echo ${{ needs.pre-req.outputs.SECRET_ENV }} 

    - name: Run a multi-line script
      run: |
        var1 = ${{ needs.pre-req.outputs.SECRET_ENV }}
        echo ${{ var1 }}
      


  test_on_merge:
    if: (github.event.action == 'closed' || github.event.pull_request.merged == true)
    needs: pre-req
    name: Destroy Infra
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      run: |
        echo "${{github.event}}"