name: Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize, closed]

env:
  AWS_REGION: "us-east-1"

jobs:
  pre-req:
    name: Setting up pre-req
    runs-on: ubuntu-latest
    outputs:
      SECRET_ENV: ${{ steps.secret-env.outputs.SECRET_ENV }}
      AWS_ACCESS_KEY: ${{ steps.secret-name.outputs.ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ steps.secret-name.outputs.SECRET_ACCESS_KEY }}

    steps:

    - name: Set EnvVar for Secret
      id: secret-env
      run: |
        if [[ ${{ github.head_ref || github.ref_name }} == 'master' ]]; then
            echo "SECRET_ENV=PROD" >> "$GITHUB_OUTPUT"
        else
            echo "SECRET_ENV=DEV" >> "$GITHUB_OUTPUT"
        fi

    - name: Set SecretName
      id: secret-name
      run: |
        echo "ACCESS_KEY=AWS_${{ steps.secret-env.outputs.SECRET_ENV }}_ACCESS_KEY" >> "$GITHUB_OUTPUT"
        echo "SECRET_ACCESS_KEY=AWS_${{ steps.secret-env.outputs.SECRET_ENV }}_SECRET_ACCESS_KEY" >> "$GITHUB_OUTPUT"


  test:
    if: (!(github.event.action == 'closed' || github.event.pull_request.merged == true))
    needs: pre-req
    name: Create Infra
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID_NAME: ${{ needs.pre-req.outputs.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY_NAME: ${{ needs.pre-req.outputs.AWS_SECRET_ACCESS_KEY }}

    steps:

    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets[env.AWS_ACCESS_KEY_ID_NAME] }}
        aws-secret-access-key: ${{ secrets[env.AWS_SECRET_ACCESS_KEY_NAME] }}
        aws-region: ${{ env.AWS_REGION }}

      


  test_on_merge:
    if: (github.event.action == 'closed' || github.event.pull_request.merged == true)
    needs: pre-req
    name: Destroy Infra
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      run: |
        echo "${{github.event}}"