name: Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize, closed]

jobs:
  test:
    if: (!(github.event.action == 'closed' || github.event.pull_request.merged == true))
    name: Create Infra
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      uses: actions/checkout@v2

    # - name: Extract branch name
    #   shell: bash
    #   run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
    #   id: extract_branch

        
    
    - name: Echo Env
      run: |
        echo ${{ github.head_ref || github.ref_name }} 


  test_on_merge:
    if: (github.event.action == 'closed' || github.event.pull_request.merged == true)
    name: Destroy Infra
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      run: |
        echo "${{github.event}}"