name: Build
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize, closed]

jobs:
  test:
    name: Create Infra
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      run: |
        echo "${{github.event}}"

  test_on_merge:
    name: Destroy Infra
    runs-on: ubuntu-latest

    steps:

    - name: Check out code
      run: |
        echo "${{github.event}}"